name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'k8s/**'

env:
  PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
  GIT_EMAIL: ${{ secrets.GIT_EMAIL }}

jobs:

  lint:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install linters
        run: |
          npm install -g htmlhint stylelint stylelint-config-standard

      - name: Lint HTML
        run: htmlhint index.html

      - name: Lint CSS
        run: stylelint "style.css"

  build-and-push:
    if: github.actor != 'github-actions[bot]'
    needs: lint
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/static-site-argocd:${{ github.sha }} .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/static-site-argocd:${{ github.sha }}

      - name: Update Kubernetes manifests
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"          
          sed -i "s|image:.*|image: ${{ secrets.DOCKER_USERNAME }}/static-site-argocd:${{ github.sha }}|g" k8s/static-site-argocd.yaml

      - name: Commit updated manifests
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://Jozefcvik:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }}.git
          git add k8s/static-site-argocd.yaml
          git commit -m "Update image to ${{ github.sha }}"
          git push origin main

#  deploy:
#   needs: build-and-push
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: ArgoCD Sync
#        run: |
#          argocd app sync static-site-app --auth-token ${{ secrets.ARGOCD_TOKEN }} --server ${{ secrets.ARGOCD_SERVER }}
